services:
  web:
    build: .
    container_name: django_debug
    ports:
      - "8000:8000"
      - "5678:5678"
    environment:
      - DJANGO_DEBUG=${DJANGO_DEBUG:-True}
    volumes:
      - .:/app
      - ./profiler_data:/app/profiler_data
#    depends_on:
#      - db

#  db:
#    image: postgres:15
#    container_name: postgres_db
#    restart: always
#    environment:
#      POSTGRES_DB: mydatabase
#      POSTGRES_USER: myuser
#      POSTGRES_PASSWORD: mypassword
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#
#volumes:
#  postgres_data:
